# -*- coding: utf-8 -*-
"""A* Maze Solver Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GcmIsB7squUQBmWtXZA44C_wcRQBEA5D
"""

import heapq
import matplotlib.pyplot as plt
import numpy as np
import time

# Heuristic: Manhattan Distance
def heuristic(a, b):
    return abs(a[0] - b[0]) + abs(a[1] - b[1])

def astar_visual(maze, start, goal):
    rows, cols = len(maze), len(maze[0])

    open_list = []
    heapq.heappush(open_list, (0, start))

    came_from = {}
    g_score = {start: 0}

    visited = set()

    while open_list:
        _, current = heapq.heappop(open_list)
        visited.add(current)

        # Visualization
        draw_grid(maze, start, goal, visited, current)
        time.sleep(0.1)

        if current == goal:
            path = []
            while current in came_from:
                path.append(current)
                current = came_from[current]
            path.append(start)
            return path[::-1]

        for dx, dy in [(0,1),(1,0),(0,-1),(-1,0)]:
            neighbor = (current[0] + dx, current[1] + dy)

            if 0 <= neighbor[0] < rows and 0 <= neighbor[1] < cols:
                if maze[neighbor[0]][neighbor[1]] == 1:
                    continue

                temp_g = g_score[current] + 1

                if neighbor not in g_score or temp_g < g_score[neighbor]:
                    g_score[neighbor] = temp_g
                    f = temp_g + heuristic(neighbor, goal)
                    heapq.heappush(open_list, (f, neighbor))
                    came_from[neighbor] = current

    return None

def draw_grid(maze, start, goal, visited, current, path=None):
    grid = np.array(maze)

    plt.clf()

    # Draw base grid
    plt.imshow(grid, cmap="gray_r")

    # Visited nodes
    for node in visited:
        plt.scatter(node[1], node[0], color='blue', s=50)

    # Current node
    plt.scatter(current[1], current[0], color='yellow', s=100)

    # Start & Goal
    plt.scatter(start[1], start[0], color='green', s=100, label="Start")
    plt.scatter(goal[1], goal[0], color='red', s=100, label="Goal")

    # Final path
    if path:
        for node in path:
            plt.scatter(node[1], node[0], color='purple', s=100)

    plt.legend()
    plt.pause(0.01)

# Example Maze
maze = [
    [0, 0, 0, 1, 0, 0],
    [1, 1, 0, 1, 0, 0],
    [0, 0, 0, 0, 0, 1],
    [0, 1, 1, 1, 0, 0],
    [0, 0, 0, 0, 0, 0]
]

start = (0, 0)
goal = (4, 5)

plt.figure(figsize=(6,6))

path = astar_visual(maze, start, goal)

# Show final path
if path:
    draw_grid(maze, start, goal, set(), goal, path)
    print("Path found:", path)
else:
    print("No path found")

plt.show()